### ISSUE TITLE
Add a change log to keep track of URIs/commits

### ISSUE THREAD

**Issue by dariocravero** [zpratt/react-tdd-guide#2]
Hi Zach,

Great guide :) I really like the way you're using commits to document stuff, very clever! Let's see how inline commenting on those plays out.

Have you thought about adding a change log and applying some versioning/tagging scheme?
That would give you, on a per commit basis, the ability to build up a list of snippets with their solution. Tagging would also make it easier to reference the code in an easier to read way.

Darío

**Comment by zpratt** [comment]
@dariocravero, I like that idea. Anything that will make the red-green-refactor steps easier to follow will add tremendous value.

**Comment by dariocravero** [comment]
Good stuff :)
